"""
ONNX embedding regression: ai_service must produce the same vectors as the
previous torch + sentence-transformers implementation, because the vectors
already stored in Atlas came from it (a mismatch would silently degrade
search until everything was re-embedded).

Reference vectors live in tests/fixtures/minilm_reference_vectors.json,
generated by the torch implementation at commit 97d91d1.

The comparison needs the model files: they're used from EMBEDDING_MODEL_DIR,
or downloaded on first use. If neither is possible (offline, no files), those
tests are skipped rather than failed -- the failure-behaviour tests still run.
"""

import json
from pathlib import Path

import numpy as np
import pytest

from app.config.settings import settings
from app.services import ai_service

FIXTURE = json.loads(
    (Path(__file__).parent / "fixtures" / "minilm_reference_vectors.json").read_text(encoding="utf-8")
)


@pytest.fixture(scope="module")
def model_available():
    try:
        ai_service._get_model()
    except Exception as exc:  # no files and no network, etc.
        pytest.skip(f"embedding model unavailable: {exc}")


def test_reference_fixture_matches_pinned_model():
    # Changing the model or revision needs a regenerated fixture (and a --force backfill).
    assert FIXTURE["model"] == settings.EMBEDDING_MODEL
    assert FIXTURE["model_revision"] == settings.EMBEDDING_MODEL_REVISION


@pytest.mark.parametrize("case", FIXTURE["cases"], ids=lambda c: c["text"][:30])
async def test_onnx_vectors_match_torch_reference(model_available, case):
    vector = await ai_service.embed_text(case["text"])

    assert vector is not None
    got, expected = np.array(vector), np.array(case["vector"])
    assert got.shape == (settings.EMBEDDING_DIMENSIONS,)
    assert abs(np.linalg.norm(got) - 1.0) < 1e-5
    assert float(got @ expected) > 0.9999
    assert np.abs(got - expected).max() < 1e-4


# ── Failure behaviour: no model needed ────────────────────────────────────────

def _broken_load():
    raise RuntimeError("simulated model load failure")


async def test_embed_text_returns_none_when_model_cannot_load(monkeypatch):
    monkeypatch.setattr(ai_service, "_get_model", _broken_load)
    assert await ai_service.embed_text("quiet cafe") is None


async def test_warm_up_never_raises(monkeypatch):
    monkeypatch.setattr(ai_service, "_get_model", _broken_load)
    await ai_service.warm_up()  # must log, not raise -- it runs as a background task at startup


async def test_embed_text_skips_blank_input():
    assert await ai_service.embed_text("   ") is None
