import type { Business, Post, Job, User, ChatThread, Review, BusinessCategory, Deal } from "@/types";

export const businesses: Business[] = [
  {
    _id: "1",
    name: "Coffee & Co.",
    category: "Cafe",
    description: "Artisan coffee and freshly baked pastries in a cozy, plant-filled space. Perfect for remote work or catching up with friends.",
    coverImage: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&h=400&fit=crop",
    ],
    address: "Handewadi,Pune",
    city: "Pune",
    location: { lat: 18.4511, lng: 73.9456 },
    distance: "0.8 km",
    isOpen: true,
    isVerified: true,
    phone: "+91 98765 43210",
    whatsapp: "+91 98765 43210",
    timings: [
      { day: "Mon-Fri", hours: "7:00 AM - 10:00 PM" },
      { day: "Sat-Sun", hours: "8:00 AM - 11:00 PM" },
    ],
    services: ["Espresso", "Cold Brew", "Pastries", "Sandwiches", "Wi-Fi", "Meeting Room"],
    rating: 4.6,
    reviewCount: 234,
    followers: 1820,
    views: 12400,
    createdAt: "2024-01-15",
    ownerId: "u2",
  },
  {
    _id: "2",
    name: "Style Studio",
    category: "Salon",
    description: "Premium unisex salon offering haircuts, coloring, facials, and bridal packages with top-tier products.",
    coverImage: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&h=400&fit=crop",
    ],
    address: "15 MG Road, Indiranagar",
    city: "Bangalore",
    location: { lat: 12.9784, lng: 77.6408 },
    distance: "1.2 km",
    isOpen: true,
    isVerified: true,
    phone: "+91 98765 11111",
    whatsapp: "+91 98765 11111",
    timings: [
      { day: "Mon-Sat", hours: "9:00 AM - 9:00 PM" },
      { day: "Sun", hours: "10:00 AM - 6:00 PM" },
    ],
    services: ["Haircut", "Hair Color", "Facial", "Manicure", "Bridal Package"],
    rating: 4.8,
    reviewCount: 512,
    followers: 3200,
    views: 28000,
    createdAt: "2023-06-20",
    ownerId: "u3",
  },
  {
    _id: "3",
    name: "City Health Clinic",
    category: "Medical",
    description: "Multi-specialty clinic with experienced doctors. Walk-ins welcome for general medicine, pediatrics, and dermatology.",
    coverImage: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&h=400&fit=crop",
    ],
    address: "88 HSR Layout, Sector 7",
    city: "Bangalore",
    location: { lat: 12.9116, lng: 77.6389 },
    distance: "2.5 km",
    isOpen: false,
    isVerified: true,
    phone: "+91 98765 22222",
    whatsapp: "+91 98765 22222",
    timings: [
      { day: "Mon-Sat", hours: "8:00 AM - 8:00 PM" },
      { day: "Sun", hours: "Closed" },
    ],
    services: ["General Medicine", "Pediatrics", "Dermatology", "Lab Tests", "Pharmacy"],
    rating: 4.3,
    reviewCount: 189,
    followers: 980,
    views: 8500,
    createdAt: "2023-11-01",
    ownerId: "u4",
  },
  {
    _id: "4",
    name: "Spice Route Kitchen",
    category: "Restaurant",
    description: "Authentic South Indian cuisine with a modern twist. Famous for our weekend thali and live dosa counter.",
    coverImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=400&fit=crop",
    ],
    address: "3 Church Street, Brigade Road",
    city: "Bangalore",
    location: { lat: 12.9742, lng: 77.6085 },
    distance: "3.1 km",
    isOpen: true,
    isVerified: false,
    phone: "+91 98765 33333",
    whatsapp: "+91 98765 33333",
    timings: [
      { day: "Daily", hours: "11:00 AM - 11:00 PM" },
    ],
    services: ["Dine-in", "Takeaway", "Delivery", "Catering", "Private Dining"],
    rating: 4.5,
    reviewCount: 678,
    followers: 4500,
    views: 35000,
    createdAt: "2022-09-10",
    ownerId: "u5",
  },
  {
    _id: "5",
    name: "Paper & Pen",
    category: "Stationery",
    description: "Curated stationery, art supplies, and planners. Home to Bangalore's best journal collection.",
    coverImage: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&h=400&fit=crop",
    ],
    address: "12 Commercial Street",
    city: "Bangalore",
    location: { lat: 12.9825, lng: 77.6090 },
    distance: "1.8 km",
    isOpen: true,
    isVerified: false,
    phone: "+91 98765 44444",
    whatsapp: "+91 98765 44444",
    timings: [
      { day: "Mon-Sat", hours: "10:00 AM - 8:00 PM" },
      { day: "Sun", hours: "11:00 AM - 5:00 PM" },
    ],
    services: ["Notebooks", "Art Supplies", "Planners", "Gift Wrapping", "Custom Orders"],
    rating: 4.7,
    reviewCount: 145,
    followers: 720,
    views: 5200,
    createdAt: "2024-03-01",
    ownerId: "u6",
  },
  {
    _id: "6",
    name: "Quick Fix Repairs",
    category: "Services",
    description: "Mobile, laptop, and appliance repairs. Same-day service with 6-month warranty on all repairs.",
    coverImage: "https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=600&h=400&fit=crop",
    ],
    address: "67 Jayanagar 4th Block",
    city: "Bangalore",
    location: { lat: 12.9292, lng: 77.5900 },
    distance: "0.5 km",
    isOpen: true,
    isVerified: true,
    phone: "+91 98765 55555",
    whatsapp: "+91 98765 55555",
    timings: [
      { day: "Mon-Sat", hours: "9:00 AM - 7:00 PM" },
      { day: "Sun", hours: "Closed" },
    ],
    services: ["Phone Repair", "Laptop Repair", "Appliance Repair", "Data Recovery"],
    rating: 4.4,
    reviewCount: 310,
    followers: 1560,
    views: 15600,
    createdAt: "2023-02-14",
    ownerId: "u7",
  },
];

export const posts: Post[] = [
  {
    id: "p1",
    businessId: "b1",
    businessName: "The Brew Barn",
    businessAvatar: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=80&h=80&fit=crop",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=600&fit=crop",
    caption: "New seasonal menu just dropped! ☕ Try our Lavender Oat Latte — your taste buds will thank you.",
    likes: 142,
    comments: [
      { id: "c1", userId: "u1", userName: "Priya S.", userAvatar: "", text: "Love this! Can't wait to try it 😍", createdAt: "2025-01-20" },
      { id: "c2", userId: "u8", userName: "Rahul M.", userAvatar: "", text: "Best cafe in Koramangala hands down", createdAt: "2025-01-21" },
    ],
    createdAt: "2025-01-19",
    isLiked: false,
  },
  {
    id: "p2",
    businessId: "b2",
    businessName: "Glow Studio Salon",
    businessAvatar: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=80&h=80&fit=crop",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&h=600&fit=crop",
    caption: "Wedding season is here! 💍 Book your bridal package now and get 20% off on pre-bridal treatments.",
    likes: 89,
    comments: [],
    createdAt: "2025-01-18",
    isLiked: false,
  },
];

export const jobs: Job[] = [
  {
    id: "j1",
    businessId: "b1",
    businessName: "The Brew Barn",
    businessLogo: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=80&h=80&fit=crop",
    title: "Barista",
    description: "Looking for a passionate barista to join our team. Experience with espresso machines required.",
    location: "Koramangala, Bangalore",
    type: "Full-time",
    salary: "₹18,000 - ₹25,000/month",
    postedAt: "2025-01-15",
    isActive: true,
  },
  {
    id: "j2",
    businessId: "b2",
    businessName: "Glow Studio Salon",
    businessLogo: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=80&h=80&fit=crop",
    title: "Hair Stylist",
    description: "Experienced hair stylist needed. Must be proficient in cuts, coloring, and treatments.",
    location: "Indiranagar, Bangalore",
    type: "Full-time",
    salary: "₹22,000 - ₹35,000/month",
    postedAt: "2025-01-10",
    isActive: true,
  },
  {
    id: "j3",
    businessId: "b4",
    businessName: "Spice Route Kitchen",
    businessLogo: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=80&h=80&fit=crop",
    title: "Delivery Partner",
    description: "Need delivery partners for food delivery. Must have own two-wheeler with valid license.",
    location: "Brigade Road, Bangalore",
    type: "Part-time",
    salary: "₹12,000 - ₹18,000/month",
    postedAt: "2025-01-12",
    isActive: true,
  },
];

export const currentUser: User = {
  id: "u1",
  name: "Arjun Kumar",
  email: "arjun@example.com",
  phone: "+91 99887 76655",
  avatar: "",
  role: "user",
  followedBusinesses: ["b1", "b2"],
  appliedJobs: ["j1"],
  createdAt: "2024-06-01",
};

export const reviews: Review[] = [
  { id: "r1", userId: "u1", userName: "Arjun K.", userAvatar: "", rating: 5, text: "Amazing coffee and ambiance! My go-to workspace.", createdAt: "2025-01-10" },
  { id: "r2", userId: "u8", userName: "Sneha R.", userAvatar: "", rating: 4, text: "Great pastries but can get crowded on weekends.", createdAt: "2025-01-05" },
  { id: "r3", userId: "u9", userName: "Vikram P.", userAvatar: "", rating: 5, text: "Best cold brew in the city. Staff is super friendly.", createdAt: "2024-12-28" },
];

export const deals: Deal[] = [
  // Coffee & Co. (id: "1")
  {
    id: "d1",
    businessId: "1",
    title: "Morning Brew Special",
    description: "Start your day right — 20% off on all beverages ordered before 9 AM.",
    discount: "20% off",
    validUntil: "2025-03-31",
    tag: "Early Bird",
    isActive: true,
  },
  {
    id: "d2",
    businessId: "1",
    title: "Work From Cafe Bundle",
    description: "All-day Wi-Fi + filter coffee + a snack of your choice at a special bundled rate.",
    discount: "₹80 off",
    originalPrice: "₹350",
    dealPrice: "₹270",
    validUntil: "2025-04-15",
    tag: "Members Only",
    isActive: true,
  },
  // Style Studio (id: "2")
  {
    id: "d3",
    businessId: "2",
    title: "Weekend Glow Package",
    description: "Treat yourself — 30% off on all facial and skin treatments every Saturday and Sunday.",
    discount: "30% off",
    validUntil: "2025-03-30",
    tag: "Weekend Special",
    isActive: true,
  },
  {
    id: "d4",
    businessId: "2",
    title: "Refer a Friend",
    description: "Bring a friend for any service and both of you get ₹200 off your bill.",
    discount: "₹200 off",
    validUntil: "2025-05-31",
    isActive: true,
  },
  // City Health Clinic (id: "3")
  {
    id: "d5",
    businessId: "3",
    title: "Free Health Screening",
    description: "Free blood pressure and blood sugar check-up. No appointment needed on Saturdays.",
    discount: "Free",
    validUntil: "2025-04-30",
    tag: "Limited Time",
    isActive: true,
  },
  {
    id: "d6",
    businessId: "3",
    title: "Family Consultation Package",
    description: "Book consultations for 3 or more family members together and save on each visit.",
    discount: "15% off",
    validUntil: "2025-06-30",
    isActive: true,
  },
  // Spice Route Kitchen (id: "4")
  {
    id: "d7",
    businessId: "4",
    title: "Weekend Thali Bonanza",
    description: "Order 2 weekend thalis and get the 3rd one absolutely free. Dine-in only.",
    discount: "Buy 2 Get 1",
    validUntil: "2025-03-31",
    tag: "Flash Sale",
    isActive: true,
  },
  {
    id: "d8",
    businessId: "4",
    title: "Happy Hours",
    description: "25% off on all à la carte orders placed between 3 PM and 6 PM on weekdays.",
    discount: "25% off",
    validUntil: "2025-05-31",
    isActive: true,
  },
  // Paper & Pen (id: "5")
  {
    id: "d9",
    businessId: "5",
    title: "Back to School Sale",
    description: "Up to 40% off on notebooks, planners, and stationery sets. Stock up for the semester.",
    discount: "Up to 40% off",
    validUntil: "2025-04-10",
    tag: "Flash Sale",
    isActive: true,
  },
  {
    id: "d10",
    businessId: "5",
    title: "Art Bundle Offer",
    description: "Spend ₹500 or more on art supplies and get ₹150 off automatically at checkout.",
    discount: "₹150 off",
    originalPrice: "₹500+",
    validUntil: "2025-06-01",
    isActive: true,
  },
  // Quick Fix Repairs (id: "6")
  {
    id: "d11",
    businessId: "6",
    title: "Free Device Diagnostics",
    description: "Bring in any phone or laptop for a free no-obligation diagnostic check. Walk-ins welcome.",
    discount: "Free",
    validUntil: "2025-04-30",
    tag: "Always On",
    isActive: true,
  },
  {
    id: "d12",
    businessId: "6",
    title: "First Repair Discount",
    description: "10% off on your first repair with us. Valid on mobiles, laptops, and home appliances.",
    discount: "10% off",
    validUntil: "2025-05-31",
    isActive: true,
  },
];

export const chatThreads: ChatThread[] = [
  {
    id: "t1",
    participantId: "b1",
    participantName: "The Brew Barn",
    participantAvatar: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=80&h=80&fit=crop",
    lastMessage: "Sure! We have a table ready for you at 7 PM.",
    lastMessageTime: "2 min ago",
    unreadCount: 1,
    isOnline: true,
  },
  {
    id: "t2",
    participantId: "b2",
    participantName: "Glow Studio Salon",
    participantAvatar: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=80&h=80&fit=crop",
    lastMessage: "Your appointment is confirmed for Saturday.",
    lastMessageTime: "1 hr ago",
    unreadCount: 0,
    isOnline: false,
  },
];

export const categories: { name: BusinessCategory; icon: string; color: string }[] = [
  { name: "Cafe", icon: "☕", color: "bg-amber-50 text-amber-700" },
  { name: "Salon", icon: "💇", color: "bg-pink-50 text-pink-700" },
  { name: "Medical", icon: "🏥", color: "bg-blue-50 text-blue-700" },
  { name: "Restaurant", icon: "🍽️", color: "bg-orange-50 text-orange-700" },
  { name: "Stationery", icon: "📝", color: "bg-violet-50 text-violet-700" },
  { name: "Services", icon: "🔧", color: "bg-emerald-50 text-emerald-700" },
  { name: "Others", icon: "📦", color: "bg-slate-50 text-slate-700" },
];
